import Container from '@/components/layout/header/container/container';
import { Header } from '@/components/layout/header/header';
import type { Metadata } from 'next';
import { Sen } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './globals.css';

const sen = Sen({ subsets: ['latin'] });
// const poppins= Poppins({ subsets:[ "latin" ]});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='pt_BR'>
			<body className={`${sen.className} antialiased`}>
				<Header />
				<Container>{children}</Container>
				<Toaster position='bottom-right' />
			</body>
		</html>
	);
}
